export interface WorkProject {
  slug: string
  client: string
  title: string
  category: 'OTT Production' | 'Brand Film' | 'Micro Drama' | 'Ad Creative' | 'Social'
  year: string
  video: string
  poster: string
  tags: string[]
  brief: string
  vertical: boolean        // true = 9:16 grid thumbnail, false = 4:3 grid thumbnail
  playerVertical?: boolean // overrides vertical for the detail page video player only
  heroPoster?: string      // overrides poster for the detail page hero background only
}

export const ALL_PROJECTS: WorkProject[] = [

  // ── OTT Production ─────────────────────────────────────────────
  {
    slug:     'the-holy-tirthankars',
    client:   'Nandi Pictures Originals',
    title:    'The Holy Tirthankars',
    category: 'OTT Production',
    year:     '2025',
    video:    '/videos/the-holy-tirthankars.mp4',
    poster:   '/posters/the-holy-tirthankars.webp',
    tags:     ['OTT', '24 Episodes', 'Spiritual'],
    brief:    '24 Tirthankaras: Ancient Wisdom from Daaji\'s Book',
    vertical: false,
  },
  {
    slug:     'kapil-muni',
    client:   'Nandi Pictures Originals',
    title:    'Kapil Muni',
    category: 'OTT Production',
    year:     '2025',
    video:    '/videos/kapil-muni.mp4',
    poster:   '/posters/kapil-muni.webp',
    tags:     ['OTT', '5 Episodes', 'Spiritual'],
    brief:    'Story of a muni when he went to an area guarded by goons.',
    vertical: false,
  },
  {
    slug:     'dharmruchi-angaar',
    client:   'Nandi Pictures Originals',
    title:    'Dharmruchi Angaar',
    category: 'OTT Production',
    year:     '2025',
    video:    '/videos/dharmruchi-angaar.mp4',
    poster:   '/posters/dharmruchi-angaar.webp',
    tags:     ['OTT', '5 Episodes', 'Spiritual'],
    brief:    'Story of a muni who sacrificed his life.',
    vertical: false,
  },
  {
    slug:     'ramayana',
    client:   'Devam Originals',
    title:    'Ramayana',
    category: 'OTT Production',
    year:     '2025',
    video:    '/videos/ramayana.mp4',
    poster:   '/posters/ramayana.webp',
    tags:     ['OTT', 'Festival', 'Spiritual'],
    brief:    'Short film tribute to Ram Navami - joy, devotion, and storytelling.',
    vertical: false,
  },

  // ── Brand Film ─────────────────────────────────────────────────
  {
    slug:     'adani-ndtv',
    client:   'Adani X NDTV',
    title:    'FutureX Quiz Announcement',
    category: 'Brand Film',
    year:     '2025',
    video:    '/videos/adani-ndtv.mp4',
    poster:   '/posters/adani-ndtv.webp',
    heroPoster: '/posters/adani-ndtv-hero.webp',
    tags:     ['Brand Film', 'TV Commercial', '4K'],
    brief:    'Adani X NDTV futureX quiz announcement TV video',
    vertical: false,
  },
  {
    slug:     'meesho',
    client:   'Meesho',
    title:    'Animatic',
    category: 'Brand Film',
    year:     '2025',
    video:    '/videos/meesho.mp4',
    poster:   '/posters/meesho.webp',
    tags:     ['Brand Film', 'Regional', '4K'],
    brief:    'Animatics crafted for Meesho\'s South India region, set against a traditional South Indian backdrop.',
    vertical: false,
  },
  {
    slug:     'jito',
    client:   'JITO',
    title:    'Showcase Video',
    category: 'Brand Film',
    year:     '2025',
    video:    '/videos/jito.mp4',
    poster:   '/posters/jito.webp',
    tags:     ['Brand Film', 'Business', '4K'],
    brief:    'A video celebrating the members and spirit of the JITO Meetup community.',
    vertical: false,
  },
  {
    slug:     'swiggy',
    client:   'Swiggy',
    title:    'New Product Launch',
    category: 'Brand Film',
    year:     '2025',
    video:    '/videos/swiggy.mp4',
    poster:   '/posters/swiggy.webp',
    tags:     ['Brand Film', 'Launch', '4K'],
    brief:    'A new product launch campaign introducing Swiggy Noice - bringing bold, youthful energy to the brand\'s latest offering.',
    vertical: false,
  },
  {
    slug:     'cars24',
    client:   'Cars24',
    title:    'Service Launch',
    category: 'Brand Film',
    year:     '2025',
    video:    '/videos/cars24.mp4',
    poster:   '/posters/cars24.webp',
    tags:     ['Brand Film', 'Launch', '4K'],
    brief:    'An ad campaign for Cars24 spotlighting their 30-day return policy - building consumer trust and redefining confidence in second-hand car buying.',
    vertical: false,
  },

  // ── Micro Drama ────────────────────────────────────────────────
  {
    slug:       'madhusudhan-ghee',
    client:     'Madhusudhan Ghee',
    title:      'Shakumbhari Devi Mandir',
    category:   'Micro Drama',
    year:       '2025',
    video:      '/videos/madhusudhan-ghee.mov',
    poster:     '/posters/madhusudhan-ghee.webp',
    heroPoster: '/posters/madhusudhan-ghee-hero.webp',
    tags:       ['Micro Drama', 'Temple Story', '4K'],
    brief:      'A devotional content series on Maa Shakumbhari Devi - weaving spiritual storytelling with seamless integration of Madhusudan\'s products.',
    vertical:   true,
  },
  {
    slug:       'vama',
    client:     'VAMA',
    title:      'VAMA TV',
    category:   'Micro Drama',
    year:       '2025',
    video:      '/videos/vama.mov',
    poster:     '/posters/vama.webp',
    heroPoster: '/posters/vama-hero.webp',
    tags:       ['Micro Drama', 'OTT', '4K'],
    brief:      'Created original micro dramas for VAMA App\'s newly launched feature, VAMA TV - blending sharp storytelling with platform-native content.',
    vertical:   true,
  },
  {
    slug:       'vaishno-devi',
    client:     'Devam',
    title:      'Vaishno Devi',
    category:   'Micro Drama',
    year:       '2025',
    video:      '/videos/vaishno-devi.mp4',
    poster:     '/posters/vaishno-devi.webp',
    heroPoster: '/posters/vaishno-devi-hero.webp',
    tags:       ['Micro Drama', 'Story', '4K'],
    brief:      'A sacred storytelling piece on Maa Vaishno Devi - capturing the divine journey, deep-rooted faith, and spiritual significance of one of India\'s most revered pilgrimages.',
    vertical:   true,
  },
  {
    slug:       'kedarnath',
    client:     'Devam',
    title:      'Kedarnath',
    category:   'Micro Drama',
    year:       '2025',
    video:      '/videos/kedarnath.mp4',
    poster:     '/posters/kedarnath.webp',
    heroPoster: '/posters/kedarnath-hero.webp',
    tags:       ['Micro Drama', 'Story', '4K'],
    brief:      'A sacred story of Kedarnath Dham - bringing to life the mystical legacy, ancient devotion, and divine aura of one of the holiest Shiva shrines.',
    vertical:   true,
  },

  // ── Ad Creative ────────────────────────────────────────────────
  {
    slug:       'wildstone-ultra-sensual',
    client:     'Wildstone',
    title:      'Ultra Sensual',
    category:   'Ad Creative',
    year:       '2025',
    video:      '/videos/wildstone-ultra-sensual.mp4',
    poster:     '/posters/wildstone-ultra-sensual.webp',
    heroPoster: '/posters/wildstone-ultra-sensual-hero.webp',
    tags:       ['Performance', 'International', '4K'],
    brief:      'A performance marketing ad crafted for Wildstone\'s entry into the US market - designed to drive conversions through bold, targeted creatives.',
    vertical:   true,
  },
  {
    slug:           'wildstone-edge',
    client:         'Wildstone',
    title:          'Edge',
    category:       'Ad Creative',
    year:           '2025',
    video:          '/videos/wildstone-edge.mp4',
    poster:         '/posters/wildstone-edge.webp',
    heroPoster:     '/posters/wildstone-edge-hero.webp',
    tags:           ['Performance', 'International', '4K'],
    brief:          'A performance marketing ad crafted for Wildstone\'s entry into the US market - translating the brand\'s edge for an international audience.',
    vertical:        true,
    playerVertical:  false,
  },
  {
    slug:       'rabitat',
    client:     'Rabitat',
    title:      'Product Marketing',
    category:   'Ad Creative',
    year:       '2025',
    video:      '/videos/rabitat.mp4',
    poster:     '/posters/rabitat.webp',
    heroPoster: '/posters/rabitat-hero.webp',
    tags:       ['Performance', 'Product', '4K'],
    brief:      'Extensive creation of performance marketing ads for Rabitat\'s bottle category - a high-volume creative suite built to test, optimise, and deliver results.',
    vertical:   true,
  },
  {
    slug:       'goodscore',
    client:     'Goodscore',
    title:      'Product Marketing',
    category:   'Ad Creative',
    year:       '2025',
    video:      '/videos/goodscore.mp4',
    poster:     '/posters/goodscore.webp',
    heroPoster: '/posters/goodscore-hero.webp',
    tags:       ['Performance', 'Product', '4K'],
    brief:      'Performance marketing videos for Goodscore App - conversion-focused, data-driven creatives that communicate the app\'s value proposition clearly.',
    vertical:   true,
  },

  // ── Social ─────────────────────────────────────────────────────
  {
    slug:       'kissansay',
    client:     'KissanSay',
    title:      'Storytelling',
    category:   'Social',
    year:       '2025',
    video:      '/videos/kissansay.mp4',
    poster:     '/posters/kissansay.webp',
    heroPoster: '/posters/kissansay-hero.webp',
    tags:       ['Social', 'Reels', '4K'],
    brief:      'Authentic, organic storytelling content for Kissansay\'s natural products - rooted in honesty, simplicity, and a deep respect for nature.',
    vertical:   true,
  },
  {
    slug:       'bharat-ki-soch',
    client:     'Bharat Ki Soch',
    title:      'Storytelling',
    category:   'Social',
    year:       '2025',
    video:      '/videos/bharat-ki-soch.mp4',
    poster:     '/posters/bharat-ki-soch.webp',
    heroPoster: '/posters/bharat-ki-soch-hero.webp',
    tags:       ['Social', 'Reels', '4K'],
    brief:      'Thought leadership content exploring India\'s civilisational ethos - sparking meaningful conversations around culture, heritage, and identity.',
    vertical:   true,
  },
  {
    slug:       'inyou',
    client:     'InYou',
    title:      'Product Marketing',
    category:   'Social',
    year:       '2025',
    video:      '/videos/inyou.mp4',
    poster:     '/posters/inyou.webp',
    heroPoster: '/posters/inyou-hero.webp',
    tags:       ['Social', 'Product', '4K'],
    brief:      'Product marketing videos for InYou - translating the brand\'s core essence into visually compelling narratives that connect and drive consumer intent.',
    vertical:   true,
  },
  {
    slug:       'mederma',
    client:     'Mederma',
    title:      'UGC',
    category:   'Social',
    year:       '2025',
    video:      '/videos/mederma.mp4',
    poster:     '/posters/mederma.webp',
    heroPoster: '/posters/mederma-hero.webp',
    tags:       ['Social', 'UGC', '4K'],
    brief:      'Product marketing videos for Mederma - credible, benefit-led storytelling that builds brand trust while communicating product efficacy.',
    vertical:   true,
  },
  {
    slug:       'country-delight',
    client:     'Country Delight',
    title:      'Drama',
    category:   'Social',
    year:       '2025',
    video:      '/videos/country-delight.mp4',
    poster:     '/posters/country-delight.webp',
    heroPoster: '/posters/country-delight-hero.webp',
    tags:       ['Social', 'Product', '4K'],
    brief:      'A heartwarming Children\'s Day campaign for Country Delight - celebrating the joy, curiosity, and wholesome spirit of childhood.',
    vertical:   true,
  },
  {
    slug:       'revision-app',
    client:     'Revision App',
    title:      'Education',
    category:   'Social',
    year:       '2025',
    video:      '/videos/revision-app.mp4',
    poster:     '/posters/revision-app.webp',
    heroPoster: '/posters/revision-app-hero.webp',
    tags:       ['Social', 'Lesson', '4K'],
    brief:      'Engaging geography teaching videos for an EdTech platform - transforming complex concepts into visually rich, immersive content for students.',
    vertical:   true,
  },
]

export function getProjectBySlug(slug: string): WorkProject | undefined {
  return ALL_PROJECTS.find(p => p.slug === slug)
}
